### ISSUE TITLE
mysql connection fails, seems like it is trying postgres

### ISSUE THREAD

**Issue by jimmy-tfp** [lorint/brick#1]
Hi,

I am trying this out against my mysql db.
I am getting this error which looks like it is trying postgress not mysql (note the pg_)

```
/Users/eysines/.rvm/gems/ruby-3.0.0/gems/activerecord-7.0.3.1/lib/active_record/sanitization.rb:203:in `raise_if_bind_arity_mismatch': wrong number of bind variables (0 for 2) in: SELECT t.table_schema AS schema, t.table_name AS relation_name, t.table_type, (ActiveRecord::PreparedStatementInvalid)
          c.column_name, c.data_type,
          COALESCE(c.character_maximum_length, c.numeric_precision) AS max_length,
          tc.constraint_type AS const, kcu.constraint_name AS "key",
          c.is_nullable
        FROM INFORMATION_SCHEMA.tables AS t
          LEFT OUTER JOIN INFORMATION_SCHEMA.columns AS c ON t.table_schema = c.table_schema
            AND t.table_name = c.table_name
          LEFT OUTER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS kcu ON
            -- ON kcu.CONSTRAINT_CATALOG = t.table_catalog AND
            kcu.CONSTRAINT_SCHEMA = c.table_schema
            AND kcu.TABLE_NAME = c.table_name
            AND kcu.position_in_unique_constraint IS NULL
            AND kcu.ordinal_position = c.ordinal_position
          LEFT OUTER JOIN INFORMATION_SCHEMA.table_constraints AS tc
            ON kcu.CONSTRAINT_SCHEMA = tc.CONSTRAINT_SCHEMA
            AND kcu.TABLE_NAME = tc.TABLE_NAME
            AND kcu.CONSTRAINT_NAME = tc.constraint_name
        WHERE t.table_schema NOT IN ('information_schema', 'pg_catalog')
          AND t.table_schema = COALESCE(current_setting('SEARCH_PATH'), 'public')
  --          AND t.table_type IN ('VIEW') -- 'BASE TABLE', 'FOREIGN TABLE'
          AND t.table_name NOT IN ('pg_stat_statements', ?, ?)
        ORDER BY 1, t.table_type DESC, c.ordinal_position
	from /Users/eysines/.rvm/gems/ruby-3.0.0/gems/activerecord-7.0.3.1/lib/active_record/sanitization.rb:159:in `replace_bind_variables'
	from /Users/eysines/.rvm/gems/ruby-3.0.0/gems/activerecord-7.0.3.1/lib/active_record/sanitization.rb:130:in `sanitize_sql_array'
	from /Users/eysines/.rvm/gems/ruby-3.0.0/gems/brick-1.0.59/lib/brick.rb:548:in `execute_sql'
	from /Users/eysines/.rvm/gems/ruby-3.0.0/gems/brick-1.0.59/lib/brick/extensions.rb:1431:in `_brick_reflect_tables'
	from /Users/eysines/.rvm/gems/ruby-3.0.0/gems/brick-1.0.59/lib/brick/extensions.rb:1297:in `establish_connection'
```

Thanks,
Jimmy

**Comment by lorint** [comment]
Hi Jimmy -- thanks so much for reaching out!

This has given me a chance to play with MySql quite a bit today.  Must confess that I had left support for anything non-Postgres related on the back burner while a large number of new features had made their way into The Brick.  Have released two updates today -- the first, version 1.0.60, allows MySQL to work with all pages except those with a `belongs_to`.  The second fixes issues determining foreign keys that are used, causing models with `belongs_to` to function.

To apply the latest version of the gem, in a terminal window simply run:

```bundle update brick```

Then the newest version should be applied, indicated by the messages `Fetching brick 1.0.61` and `Installing brick 1.0.61`.  Would welcome your feedback as you get a chance to experiment with the updates.
