### ISSUE TITLE
`Brick.path_prefix = 'brick'` causes error with `rails g scaffold ModelName`

### ISSUE THREAD

**Issue by stv8** [lorint/brick#21]
First off as a newcomer to the Rails ecosystem, this package is amazing and felt like magic using it. I could not believe how well it works with an existing database 😄 

With that said I encountered I an error when running `rails g scaffold ModelName` which occurs when the `Brick.path_prefix = 'brick'` option is set

**Versions:**
- `ruby: 3.3.5`
- `rails: 7.2.1`
- `brick: 1.0.217`

**Thread I posted in the Rails forum with more info**
https://discuss.rubyonrails.org/t/error-when-running-rails-g-scaffold-photo-undefined-method-all-for-module-activemodel-nomethoderror/86799/10

<details>

<summary>Full Stack Trace of Error</summary>

```
invoke  active_record
      create    db/migrate/20240927035144_create_photos.rb
      create    app/models/photo.rb
      invoke    test_unit
      create      test/models/photo_test.rb
      create      test/fixtures/photos.yml
      invoke  resource_route
       route    resources :photos
      invoke  scaffold_controller
Users/prometheus/.gem/ruby/3.3.5/gems/jbuilder-2.13.0/lib/generators/rails/templates/controller.rb:11:in `block in template': undefined method `all' for module ActiveModel (NoMethodError)
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:347:in `block in capture'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:354:in `with_output_buffer'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:347:in `capture'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators/base.rb:297:in `module_namespacing'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/jbuilder-2.13.0/lib/generators/rails/templates/controller.rb:5:in `template'
        from /Users/prometheus/.rubies/ruby-3.3.5/lib/ruby/3.3.0/erb.rb:429:in `eval'
        from /Users/prometheus/.rubies/ruby-3.3.5/lib/ruby/3.3.0/erb.rb:429:in `result'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:128:in `block in template'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/create_file.rb:54:in `render'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/create_file.rb:47:in `identical?'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/create_file.rb:74:in `on_conflict_behavior'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/create_file.rb:61:in `invoke!'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions.rb:93:in `action'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/create_file.rb:25:in `create_file'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/actions/file_manipulation.rb:124:in `template'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators/named_base.rb:25:in `block in template'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators/named_base.rb:45:in `inside_template'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators/named_base.rb:24:in `template'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators/rails/scaffold_controller/scaffold_controller_generator.rb:24:in `create_controller_files'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `each'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `map'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `invoke_all'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/group.rb:243:in `dispatch'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:116:in `invoke'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/group.rb:288:in `block in _invoke_for_class_method'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/shell.rb:68:in `with_padding'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/group.rb:277:in `_invoke_for_class_method'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/group.rb:134:in `_invoke_from_option_scaffold_controller'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `block in invoke_all'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `each'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `map'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:134:in `invoke_all'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/group.rb:243:in `dispatch'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/base.rb:584:in `start'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/generators.rb:261:in `invoke'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/commands/generate/generate_command.rb:26:in `perform'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/command.rb:28:in `run'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/thor-1.3.2/lib/thor.rb:538:in `dispatch'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/command/base.rb:73:in `perform'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/command.rb:71:in `block in invoke'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/command.rb:149:in `with_argv'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/command.rb:69:in `invoke'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/railties-7.2.1/lib/rails/commands.rb:18:in `<main>'
        from /Users/prometheus/.rubies/ruby-3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
        from /Users/prometheus/.rubies/ruby-3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
        from /Users/prometheus/.gem/ruby/3.3.5/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

</details>

**Steps to Reproduce:**

1. `rails new site`
2. `cd site && bundle add brick`
3. `bin/rails g brick:install`
4. `rails g scaffold Foo` <-- Succeeds
5. uncomment line 15 in `config/initializers/brick.rb` which sets the brick path, e.g. ` ::Brick.path_prefix = 'brick'`
6. `rails g scaffold Bar` <-- Error

I'm fairly new to Ruby and Rails and unsure how to debug further, so let me know if you need any more info.

**Comment by lorint** [comment]
> First off as a newcomer to the Rails ecosystem, this package is amazing and felt like magic using it. I could not believe how well it works with an existing database 😄

Thanks so much for your feedback -- it's been quite a journey in order to get it to this point -- testing against _lots_ of different projects!

Also thanks for the simple instructions about how to reproduce this bug.  As part of identifying the fix I've examined very closely how Brick should be trying to locate existing classes.  This gem overrides `const_missing` in order to make everything feel so seamless -- anytime code looks for a missing model, controller, or module then a check is made to see if an existing database table could potentially become a resource for this.  If so then Brick auto-creates and returns this class, all of it having been built on-the-fly in RAM.  If it's unloaded for whatever reason then again it can be auto-created if needed.

In this case the fix has allowed me to simplify existing code, removing some nuanced checks that I thought were essential for another app that I've been working with.  It appears that based on an update to Zeitwerk that this original more involved fix is no longer needed, and the checks in Brick could be simplified.  I'll be doing further testing against many other projects to confirm that I'm not missing anything important.  For the moment all the basic Rails apps that I test against are working, so I'm going to ship this update.

Brick 1.0.218 includes the fix for:
```
... undefined method 'all' for module ActiveModel (NoMethodError)
```
Please let me know if you find anything else that is out of the ordinary.

Thanks so much for reporting this issue!

**Comment by stv8** [comment]
wow quick fix that's awesome! thanks for the explanation and I will be updating tonight, cheers!
